name: setup_node
description: Setup Node, and install Pnpm
inputs:
  node-version:
    required: false
    description: The version of Node to use.
    default: '22.x'
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Enable Corepack
      run: |
        npm i -g --force corepack
        corepack enable
        pnpm -v
      shell: bash
