packages:
  - test-packages/*

minimumReleaseAge: 2880 # two days
minimumReleaseAgeExclude:
  - 'vscode'
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - undici-types@6.21.0
allowBuilds:
  unrs-resolver: true
  esbuild: true

# cspell:dictionaries npm
